NAME="Proper Linux"
VERSION="0.1"
ID="proper"
ID_LIKE="fedora"
PRETTY_NAME="Proper Linux 0.1 (Fedora KDE derivative)"
HOME_URL="https://github.com/marcodenic/PROPER_LINUX"
SUPPORT_URL="https://github.com/marcodenic/PROPER_LINUX/issues"
BUG_REPORT_URL="https://github.com/marcodenic/PROPER_LINUX/issues"
