font-family = JetBrains Mono
font-size = 12
background = 11151d
foreground = f1f4f8
cursor-color = 91b4ff
selection-background = 344965
selection-foreground = ffffff
background-opacity = 0.50
background-opacity-cells = true
background-blur = false
cursor-style = block
window-padding-x = 16
window-padding-y = 14
window-padding-balance = true
window-width = 100
window-height = 30
shell-integration-features = cursor,sudo,title
window-decoration = true
confirm-close-surface = false
