font-family = JetBrains Mono
font-size = 12
background = 111827
foreground = e5e7eb
cursor-color = 8bd5ca
cursor-style = block
window-padding-x = 16
window-padding-y = 14
window-padding-balance = true
shell-integration-features = cursor,sudo,title
window-decoration = true
confirm-close-surface = false
