#!/usr/bin/python3
"""Generate Proper's translucent and dense Plasma panel materials."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def inline_map(source: str, label: str) -> dict[str, str]:
    match = re.search(rf"^{re.escape(label)}:\s*\{{([^}}]+)\}}$", source, re.MULTILINE)
    if not match:
        raise ValueError(f"missing token map: {label}")
    values: dict[str, str] = {}
    for item in match.group(1).split(","):
        key, value = item.split(":", 1)
        values[key.strip()] = value.strip().strip("'")
    return values


def panel_svg(
    *,
    tint: str,
    opacity: float,
    rim: str,
    rim_opacity: float,
    radius: int,
    shadow_margin: int,
    dense: bool,
) -> str:
    centre = 36
    frame = radius * 2 + centre
    mask_x = 80
    shadow_x = 176
    shadow_corner = radius + shadow_margin
    shadow_centre_x = shadow_x + shadow_corner
    shadow_far_x = shadow_centre_x + centre
    shadow_centre_y = shadow_corner
    shadow_far_y = shadow_centre_y + centre
    mode = "dense" if dense else "translucent"

    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-FileCopyrightText: 2026 Proper Linux contributors -->
<!-- SPDX-License-Identifier: GPL-3.0-or-later -->
<!-- Generated by generate-panel-material.py from tokens.yaml ({mode}); do not edit. -->
<svg xmlns="http://www.w3.org/2000/svg" width="320" height="100" viewBox="0 0 320 100">
  <defs>
    <style id="current-color-scheme" type="text/css">
      .ColorScheme-Background {{ color: {tint}; }}
      .ColorScheme-Frame {{ color: {rim}; }}
    </style>
  </defs>

  <g id="top" transform="translate({radius} 0)">
    <rect width="{centre}" height="{radius}" fill="{tint}" fill-opacity="{opacity:.2f}"/>
    <rect width="{centre}" height="1" fill="{rim}" fill-opacity="{rim_opacity:.3f}"/>
  </g>
  <g id="bottom" transform="translate({radius} {radius + centre})">
    <rect width="{centre}" height="{radius}" fill="{tint}" fill-opacity="{opacity:.2f}"/>
    <rect y="{radius - 1}" width="{centre}" height="1" fill="{rim}" fill-opacity="{rim_opacity:.3f}"/>
  </g>
  <g id="left" transform="translate(0 {radius})">
    <rect width="{radius}" height="{centre}" fill="{tint}" fill-opacity="{opacity:.2f}"/>
    <rect width="1" height="{centre}" fill="{rim}" fill-opacity="{rim_opacity:.3f}"/>
  </g>
  <g id="right" transform="translate({radius + centre} {radius})">
    <rect width="{radius}" height="{centre}" fill="{tint}" fill-opacity="{opacity:.2f}"/>
    <rect x="{radius - 1}" width="1" height="{centre}" fill="{rim}" fill-opacity="{rim_opacity:.3f}"/>
  </g>
  <rect id="center" x="{radius}" y="{radius}" width="{centre}" height="{centre}" fill="{tint}" fill-opacity="{opacity:.2f}"/>
  <g id="topleft">
    <g opacity="{opacity:.2f}">
      <path d="M{radius} 0v{radius}H0v-1C0 6.72 6.72 0 {radius - 1} 0h1z" fill="{tint}"/>
      <rect x="{radius - 1}" width="1" height="{radius}" fill="{tint}"/>
      <rect y="{radius - 1}" width="{radius}" height="1" fill="{tint}"/>
    </g>
    <g opacity="{rim_opacity:.3f}">
      <path id="rim-topleft" d="M{radius} .5H{radius - 1}C6.99.5.5 6.99.5 {radius - 1}V{radius}" fill="none" stroke="{rim}"/>
      <rect x="{radius - 1}" width="1" height="1" fill="{rim}"/>
      <rect y="{radius - 1}" width="1" height="1" fill="{rim}"/>
    </g>
  </g>
  <g id="topright" transform="translate({radius + centre} 0)">
    <g opacity="{opacity:.2f}">
      <path d="M0 0v{radius}h{radius}v-1C{radius} 6.72 9.28 0 1 0H0z" fill="{tint}"/>
      <rect width="1" height="{radius}" fill="{tint}"/>
      <rect y="{radius - 1}" width="{radius}" height="1" fill="{tint}"/>
    </g>
    <g opacity="{rim_opacity:.3f}">
      <path id="rim-topright" d="M0 .5H1c8.01 0 14.5 6.49 14.5 14.5V{radius}" fill="none" stroke="{rim}"/>
      <rect width="1" height="1" fill="{rim}"/>
      <rect x="{radius - 1}" y="{radius - 1}" width="1" height="1" fill="{rim}"/>
    </g>
  </g>
  <g id="bottomleft" transform="translate(0 {radius + centre})">
    <g opacity="{opacity:.2f}">
      <path d="M{radius} {radius}V0H0v1c0 8.28 6.72 {radius - 1} {radius - 1} {radius - 1}h1z" fill="{tint}"/>
      <rect x="{radius - 1}" width="1" height="{radius}" fill="{tint}"/>
      <rect width="{radius}" height="1" fill="{tint}"/>
    </g>
    <g opacity="{rim_opacity:.3f}">
      <path id="rim-bottomleft" d="M{radius} {radius - .5}H{radius - 1}C6.99 {radius - .5}.5 9.01.5 1V0" fill="none" stroke="{rim}"/>
      <rect x="{radius - 1}" y="{radius - 1}" width="1" height="1" fill="{rim}"/>
      <rect width="1" height="1" fill="{rim}"/>
    </g>
  </g>
  <g id="bottomright" transform="translate({radius + centre} {radius + centre})">
    <g opacity="{opacity:.2f}">
      <path d="M0 {radius}V0h{radius}v1c0 8.28-6.72 {radius - 1}-{radius - 1} {radius - 1}H0z" fill="{tint}"/>
      <rect width="1" height="{radius}" fill="{tint}"/>
      <rect width="{radius}" height="1" fill="{tint}"/>
    </g>
    <g opacity="{rim_opacity:.3f}">
      <path id="rim-bottomright" d="M0 {radius - .5}H1c8.01 0 14.5-6.49 14.5-14.5V0" fill="none" stroke="{rim}"/>
      <rect y="{radius - 1}" width="1" height="1" fill="{rim}"/>
      <rect x="{radius - 1}" width="1" height="1" fill="{rim}"/>
    </g>
  </g>

  <rect id="hint-top-margin" x="33" width="2" height="10" fill="#ff00ff"/>
  <rect id="hint-bottom-margin" x="33" y="58" width="2" height="10" fill="#ff00ff"/>
  <rect id="hint-left-margin" y="33" width="10" height="2" fill="#ff00ff"/>
  <rect id="hint-right-margin" x="58" y="33" width="10" height="2" fill="#ff00ff"/>
  <rect id="hint-stretch-borders" x="69" width="1" height="1" fill="#ff6600"/>
  <!-- Match Plasma's own Breeze panel contract: tile the flat centre and keep
       every frame slice at one identical material opacity. -->
  <rect id="hint-tile-center" x="70" width="1" height="1" fill="#ff6600"/>

  <rect id="mask-top" x="{mask_x + radius}" width="{centre}" height="{radius}" fill="#000000"/>
  <rect id="mask-bottom" x="{mask_x + radius}" y="{radius + centre}" width="{centre}" height="{radius}" fill="#000000"/>
  <rect id="mask-left" x="{mask_x}" y="{radius}" width="{radius}" height="{centre}" fill="#000000"/>
  <rect id="mask-right" x="{mask_x + radius + centre}" y="{radius}" width="{radius}" height="{centre}" fill="#000000"/>
  <rect id="mask-center" x="{mask_x + radius}" y="{radius}" width="{centre}" height="{centre}" fill="#000000"/>
  <g id="mask-topleft">
    <path d="M{mask_x + radius} 0v{radius}H{mask_x}v-1c0-8.28 6.72-15 15-15h1z" fill="#000000"/>
    <rect x="{mask_x + radius - 1}" width="1" height="{radius}" fill="#000000"/>
    <rect x="{mask_x}" y="{radius - 1}" width="{radius}" height="1" fill="#000000"/>
  </g>
  <g id="mask-topright">
    <path d="M{mask_x + radius + centre} 0v{radius}h{radius}v-1c0-8.28-6.72-15-15-15h-1z" fill="#000000"/>
    <rect x="{mask_x + radius + centre}" width="1" height="{radius}" fill="#000000"/>
    <rect x="{mask_x + radius + centre}" y="{radius - 1}" width="{radius}" height="1" fill="#000000"/>
  </g>
  <g id="mask-bottomleft">
    <path d="M{mask_x + radius} {frame}V{radius + centre}H{mask_x}v1c0 8.28 6.72 15 15 15h1z" fill="#000000"/>
    <rect x="{mask_x + radius - 1}" y="{radius + centre}" width="1" height="{radius}" fill="#000000"/>
    <rect x="{mask_x}" y="{radius + centre}" width="{radius}" height="1" fill="#000000"/>
  </g>
  <g id="mask-bottomright">
    <path d="M{mask_x + radius + centre} {frame}V{radius + centre}h{radius}v1c0 8.28-6.72 15-15 15h-1z" fill="#000000"/>
    <rect x="{mask_x + radius + centre}" y="{radius + centre}" width="1" height="{radius}" fill="#000000"/>
    <rect x="{mask_x + radius + centre}" y="{radius + centre}" width="{radius}" height="1" fill="#000000"/>
  </g>

  <!-- This hidden prefix gives Plasma enough floating padding to retain the full shadow. -->
  <rect id="floating-center" x="150" width="1" height="1" fill="#000000" fill-opacity="0.001"/>
  <rect id="floating-hint-top-margin" x="152" width="1" height="{shadow_margin}" fill="#ff00ff"/>
  <rect id="floating-hint-bottom-margin" x="154" width="1" height="{shadow_margin}" fill="#ff00ff"/>
  <rect id="floating-hint-left-margin" x="156" width="{shadow_margin}" height="1" fill="#ff00ff"/>
  <rect id="floating-hint-right-margin" x="156" y="2" width="{shadow_margin}" height="1" fill="#ff00ff"/>

  <rect id="shadow-topleft" x="{shadow_x}" width="{shadow_corner}" height="{shadow_corner}" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-top" x="{shadow_centre_x}" width="{centre}" height="{shadow_corner}" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-topright" x="{shadow_far_x}" width="{shadow_corner}" height="{shadow_corner}" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-left" x="{shadow_x}" y="{shadow_centre_y}" width="{shadow_corner}" height="{centre}" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-center" x="{shadow_centre_x}" y="{shadow_centre_y}" width="{centre}" height="{centre}" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-right" x="{shadow_far_x}" y="{shadow_centre_y}" width="{shadow_corner}" height="{centre}" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-bottomleft" x="{shadow_x}" y="{shadow_far_y}" width="{shadow_corner}" height="{shadow_corner}" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-bottom" x="{shadow_centre_x}" y="{shadow_far_y}" width="{centre}" height="{shadow_corner}" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-bottomright" x="{shadow_far_x}" y="{shadow_far_y}" width="{shadow_corner}" height="{shadow_corner}" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-hint-top-margin" x="280" width="1" height="{shadow_margin}" fill="#ff00ff"/>
  <rect id="shadow-hint-bottom-margin" x="282" width="1" height="{shadow_margin}" fill="#ff00ff"/>
  <rect id="shadow-hint-left-margin" x="284" width="{shadow_margin}" height="1" fill="#ff00ff"/>
  <rect id="shadow-hint-right-margin" x="284" y="2" width="{shadow_margin}" height="1" fill="#ff00ff"/>
</svg>
'''


def popup_svg(
    *,
    tint: str,
    opacity: float,
    rim: str,
    rim_opacity: float,
    radius: int,
    dense: bool,
) -> str:
    """Generate the shared dialog, tooltip, notification, and OSD material."""
    if radius != 0:
        raise ValueError("popup frames are square so edge-attached dialogs cannot expose a lone corner gap")
    edge = 12
    centre = 32
    frame = edge * 2 + centre
    mask_x = 70
    mode = "dense" if dense else "translucent"

    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-FileCopyrightText: 2026 Proper Linux contributors -->
<!-- SPDX-License-Identifier: GPL-3.0-or-later -->
<!-- Generated by generate-panel-material.py from tokens.yaml ({mode} popup); do not edit. -->
<svg xmlns="http://www.w3.org/2000/svg" width="180" height="56" viewBox="0 0 180 56">
  <defs>
    <style id="current-color-scheme" type="text/css">
      .ColorScheme-Background {{ color: {tint}; }}
      .ColorScheme-Frame {{ color: {rim}; }}
    </style>
  </defs>

  <g id="top" transform="translate({edge} 0)">
    <rect width="{centre}" height="{edge}" fill="{tint}" fill-opacity="{opacity:.2f}"/>
    <rect width="{centre}" height="1" fill="{rim}" fill-opacity="{rim_opacity:.3f}"/>
  </g>
  <g id="bottom" transform="translate({edge} {edge + centre})">
    <rect width="{centre}" height="{edge}" fill="{tint}" fill-opacity="{opacity:.2f}"/>
    <rect y="{edge - 1}" width="{centre}" height="1" fill="{rim}" fill-opacity="{rim_opacity:.3f}"/>
  </g>
  <g id="left" transform="translate(0 {edge})">
    <rect width="{edge}" height="{centre}" fill="{tint}" fill-opacity="{opacity:.2f}"/>
    <rect width="1" height="{centre}" fill="{rim}" fill-opacity="{rim_opacity:.3f}"/>
  </g>
  <g id="right" transform="translate({edge + centre} {edge})">
    <rect width="{edge}" height="{centre}" fill="{tint}" fill-opacity="{opacity:.2f}"/>
    <rect x="{edge - 1}" width="1" height="{centre}" fill="{rim}" fill-opacity="{rim_opacity:.3f}"/>
  </g>
  <rect id="center" x="{edge}" y="{edge}" width="{centre}" height="{centre}" fill="{tint}" fill-opacity="{opacity:.2f}"/>
  <g id="topleft">
    <g opacity="{opacity:.2f}">
      <rect width="{edge}" height="{edge}" fill="{tint}"/>
      <rect x="{edge - 1}" width="1" height="{edge}" fill="{tint}"/>
    </g>
    <g opacity="{rim_opacity:.3f}">
      <path id="rim-topleft" d="M0 0H{edge}V1H1V{edge}H0Z" fill="{rim}"/>
      <rect x="{edge - 1}" width="1" height="1" fill="{rim}"/>
      <rect y="{edge - 1}" width="1" height="1" fill="{rim}"/>
    </g>
  </g>
  <g id="topright" transform="translate({edge + centre} 0)">
    <g opacity="{opacity:.2f}">
      <rect width="{edge}" height="{edge}" fill="{tint}"/>
      <rect width="1" height="{edge}" fill="{tint}"/>
    </g>
    <g opacity="{rim_opacity:.3f}">
      <path id="rim-topright" d="M0 0H{edge}V{edge}H{edge - 1}V1H0Z" fill="{rim}"/>
      <rect width="1" height="1" fill="{rim}"/>
      <rect x="{edge - 1}" y="{edge - 1}" width="1" height="1" fill="{rim}"/>
    </g>
  </g>
  <g id="bottomleft" transform="translate(0 {edge + centre})">
    <g opacity="{opacity:.2f}">
      <rect width="{edge}" height="{edge}" fill="{tint}"/>
      <rect x="{edge - 1}" width="1" height="{edge}" fill="{tint}"/>
    </g>
    <g opacity="{rim_opacity:.3f}">
      <path id="rim-bottomleft" d="M0 0H1V{edge - 1}H{edge}V{edge}H0Z" fill="{rim}"/>
      <rect x="{edge - 1}" y="{edge - 1}" width="1" height="1" fill="{rim}"/>
      <rect width="1" height="1" fill="{rim}"/>
    </g>
  </g>
  <g id="bottomright" transform="translate({edge + centre} {edge + centre})">
    <g opacity="{opacity:.2f}">
      <rect width="{edge}" height="{edge}" fill="{tint}"/>
      <rect width="1" height="{edge}" fill="{tint}"/>
    </g>
    <g opacity="{rim_opacity:.3f}">
      <path id="rim-bottomright" d="M{edge - 1} 0H{edge}V{edge}H0V{edge - 1}H{edge - 1}Z" fill="{rim}"/>
      <rect y="{edge - 1}" width="1" height="1" fill="{rim}"/>
      <rect x="{edge - 1}" width="1" height="1" fill="{rim}"/>
    </g>
  </g>

  <rect id="hint-top-margin" x="29" width="2" height="12" fill="#ff00ff"/>
  <rect id="hint-bottom-margin" x="29" y="44" width="2" height="12" fill="#ff00ff"/>
  <rect id="hint-left-margin" y="29" width="12" height="2" fill="#ff00ff"/>
  <rect id="hint-right-margin" x="44" y="29" width="12" height="2" fill="#ff00ff"/>
  <rect id="hint-stretch-borders" x="61" width="1" height="1" fill="#ff6600"/>
  <!-- Plasma renders these nine slices independently. A tiled centre avoids
       scaling artefacts without painting it again beneath translucent edges. -->
  <rect id="hint-tile-center" x="62" width="1" height="1" fill="#ff6600"/>

  <rect id="mask-top" x="{mask_x + edge}" width="{centre}" height="{edge}" fill="#000000"/>
  <rect id="mask-bottom" x="{mask_x + edge}" y="{edge + centre}" width="{centre}" height="{edge}" fill="#000000"/>
  <rect id="mask-left" x="{mask_x}" y="{edge}" width="{edge}" height="{centre}" fill="#000000"/>
  <rect id="mask-right" x="{mask_x + edge + centre}" y="{edge}" width="{edge}" height="{centre}" fill="#000000"/>
  <rect id="mask-center" x="{mask_x + edge}" y="{edge}" width="{centre}" height="{centre}" fill="#000000"/>
  <g id="mask-topleft">
    <rect x="{mask_x}" width="{edge}" height="{edge}" fill="#000000"/>
    <rect x="{mask_x + edge - 1}" width="1" height="{edge}" fill="#000000"/>
  </g>
  <g id="mask-topright">
    <rect x="{mask_x + edge + centre}" width="{edge}" height="{edge}" fill="#000000"/>
    <rect x="{mask_x + edge + centre}" width="1" height="{edge}" fill="#000000"/>
  </g>
  <g id="mask-bottomleft">
    <rect x="{mask_x}" y="{edge + centre}" width="{edge}" height="{edge}" fill="#000000"/>
    <rect x="{mask_x + edge - 1}" y="{edge + centre}" width="1" height="{edge}" fill="#000000"/>
  </g>
  <g id="mask-bottomright">
    <rect x="{mask_x + edge + centre}" y="{edge + centre}" width="{edge}" height="{edge}" fill="#000000"/>
    <rect x="{mask_x + edge + centre}" y="{edge + centre}" width="1" height="{edge}" fill="#000000"/>
  </g>

  <!-- Neutral slices suppress Breeze's fallback shadow without reserving an
       invisible gutter around an edge-attached popup. -->
  <rect id="shadow-center" x="150" y="10" width="20" height="20" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-top" x="150" width="20" height="10" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-bottom" x="150" y="30" width="20" height="10" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-left" x="140" y="10" width="10" height="20" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-right" x="170" y="10" width="10" height="20" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-topleft" x="140" width="10" height="10" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-topright" x="170" width="10" height="10" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-bottomleft" x="140" y="30" width="10" height="10" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-bottomright" x="170" y="30" width="10" height="10" fill="#000000" fill-opacity="0.001"/>
  <rect id="shadow-hint-top-margin" x="159" width="2" height="0.001" fill="#ff00ff"/>
  <rect id="shadow-hint-bottom-margin" x="159" y="30" width="2" height="0.001" fill="#ff00ff"/>
  <rect id="shadow-hint-left-margin" x="140" y="19" width="0.001" height="2" fill="#ff00ff"/>
  <rect id="shadow-hint-right-margin" x="170" y="19" width="0.001" height="2" fill="#ff00ff"/>
</svg>
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("tokens", type=Path)
    parser.add_argument("output", type=Path)
    arguments = parser.parse_args()

    source = arguments.tokens.read_text(encoding="utf-8")
    material = inline_map(source, "material")
    opacity = inline_map(source, "opacity")
    radius = inline_map(source, "radius")
    shadow = inline_map(source, "shadow")
    if int(radius["panel"]) != 16:
        raise ValueError("panel SVG corner paths are reviewed for the 16px Proper radius")
    if int(radius["popup"]) != 0:
        raise ValueError("popup SVG corners must remain square for edge-attached dialogs")
    arguments.output.mkdir(parents=True, exist_ok=True)

    shared = dict(
        rim=material["panel_edge"],
        rim_opacity=float(opacity["panel_edge"]),
        radius=int(radius["panel"]),
        shadow_margin=int(shadow["panel_margin"]),
    )
    (arguments.output / "panel-background.svg").write_text(
        panel_svg(tint=material["panel_tint"], opacity=float(opacity["panel"]), dense=False, **shared),
        encoding="utf-8",
    )
    (arguments.output / "solid-panel-background.svg").write_text(
        panel_svg(tint=material["panel_dense"], opacity=float(opacity["panel_dense"]), dense=True, **shared),
        encoding="utf-8",
    )
    popup_shared = dict(
        rim=material["panel_edge"],
        rim_opacity=float(opacity["popup_edge"]),
        radius=int(radius["popup"]),
    )
    (arguments.output / "popup-background.svg").write_text(
        popup_svg(tint=material["popup_tint"], opacity=float(opacity["popup"]), dense=False, **popup_shared),
        encoding="utf-8",
    )
    (arguments.output / "solid-popup-background.svg").write_text(
        popup_svg(tint=material["popup_tint"], opacity=float(opacity["panel_dense"]), dense=True, **popup_shared),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
