[Greeter]
WallpaperPluginId=org.kde.image

[Greeter][Wallpaper][org.kde.image][General]
Image=file:///usr/share/wallpapers/ProperBlueHour/contents/images/1920x1080.png
PreviewImage=file:///usr/share/wallpapers/ProperBlueHour/contents/images/1920x1080.png
