FROM quay.io/fedora/fedora@sha256:aadc45e503a9a4df93b2a30102151d5286d2869c6ba44b8fbf3918abd9ca3862

RUN dnf -y install \
        acpica-tools \
        binutils \
        gcc \
        gcc-c++ \
        gcc-x86_64-linux-gnu \
        git \
        libuuid-devel \
        make \
        nasm \
        patch \
        perl-File-Compare \
        perl-File-Copy \
        perl-FindBin \
        perl-IPC-Cmd \
        perl-JSON \
        perl-Time-Piece \
        python3-devel \
        rpm-build \
        xz \
    && dnf clean all
