FROM quay.io/fedora/fedora:44@sha256:aadc45e503a9a4df93b2a30102151d5286d2869c6ba44b8fbf3918abd9ca3862
RUN dnf -y install rpm-build curl gcc git-core gtk4-devel libadwaita-devel gtk4-layer-shell-devel pkgconf gettext pandoc oniguruma-devel qt6-qtbase-devel kf6-kwindowsystem-devel xz tar minisign && dnf clean all
